/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.0-dev at Sun Feb 18 00:49:35 2018. */

#include "messages.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t EthereumAddressSubscription_fields[6] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, EthereumAddressSubscription, to_address, to_address, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, EthereumAddressSubscription, from_address, to_address, 0),
    PB_FIELD(  3, FLOAT   , OPTIONAL, STATIC  , OTHER, EthereumAddressSubscription, value, from_address, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, EthereumAddressSubscription, hash, value, 0),
    PB_FIELD(  5, MESSAGE , OPTIONAL, STATIC  , OTHER, EthereumAddressSubscription, block, hash, &EthereumBlock_fields),
    PB_LAST_FIELD
};

const pb_field_t EthereumAddressBalance_fields[3] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, EthereumAddressBalance, address, address, 0),
    PB_FIELD(  2, FLOAT   , OPTIONAL, STATIC  , OTHER, EthereumAddressBalance, value, address, 0),
    PB_LAST_FIELD
};

const pb_field_t EthereumBlock_fields[3] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, EthereumBlock, blockNumber, blockNumber, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, EthereumBlock, blockHash, blockNumber, 0),
    PB_LAST_FIELD
};

const pb_field_t SerialMessage_fields[2] = {
    PB_FIELD(  1, BYTES   , OPTIONAL, CALLBACK, FIRST, SerialMessage, data, data, 0),
    PB_LAST_FIELD
};

const pb_field_t WhisperSubscribe_fields[6] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, WhisperSubscribe, private_key, private_key, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, WhisperSubscribe, sym_key_password, private_key, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, WhisperSubscribe, topic, sym_key_password, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, WhisperSubscribe, pubkey, topic, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, WhisperSubscribe, is_ascii, pubkey, 0),
    PB_LAST_FIELD
};

const pb_field_t TransmittedWhisperMessage_fields[7] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, TransmittedWhisperMessage, pub_key, pub_key, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, TransmittedWhisperMessage, sym_key_password, pub_key, 0),
    PB_FIELD(  3, STRING  , OPTIONAL, STATIC  , OTHER, TransmittedWhisperMessage, signature_private_key, sym_key_password, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, TransmittedWhisperMessage, topic, signature_private_key, 0),
    PB_FIELD(  5, BOOL    , OPTIONAL, STATIC  , OTHER, TransmittedWhisperMessage, is_ascii, topic, 0),
    PB_FIELD(  6, STRING  , OPTIONAL, STATIC  , OTHER, TransmittedWhisperMessage, payload, is_ascii, 0),
    PB_LAST_FIELD
};

const pb_field_t ReceivedWhisperMessage_fields[6] = {
    PB_FIELD(  1, STRING  , OPTIONAL, STATIC  , FIRST, ReceivedWhisperMessage, from, from, 0),
    PB_FIELD(  2, STRING  , OPTIONAL, STATIC  , OTHER, ReceivedWhisperMessage, topic, from, 0),
    PB_FIELD(  3, BOOL    , OPTIONAL, STATIC  , OTHER, ReceivedWhisperMessage, is_ascii, topic, 0),
    PB_FIELD(  4, STRING  , OPTIONAL, STATIC  , OTHER, ReceivedWhisperMessage, payload, is_ascii, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, ReceivedWhisperMessage, timestamp, payload, 0),
    PB_LAST_FIELD
};

const pb_field_t Error_fields[2] = {
    PB_FIELD(  1, INT32   , OPTIONAL, STATIC  , FIRST, Error, error_number, error_number, 0),
    PB_LAST_FIELD
};



/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EthereumAddressSubscription, block) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_EthereumAddressSubscription_EthereumAddressBalance_EthereumBlock_SerialMessage_WhisperSubscribe_TransmittedWhisperMessage_ReceivedWhisperMessage_Error)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(EthereumAddressSubscription, block) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_EthereumAddressSubscription_EthereumAddressBalance_EthereumBlock_SerialMessage_WhisperSubscribe_TransmittedWhisperMessage_ReceivedWhisperMessage_Error)
#endif


/* @@protoc_insertion_point(eof) */
